language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/

dist: trusty
jobs:
  include:
    - stage: ui_build
      language: node_js
      node_js: 10.15.2
      script: cd KafkaCenter-Frontend && npm install && npm run build

    - stage: GitHubRelease
      install:
        - mvn -Drevision=${TRAVIS_TAG#v} install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -Drevision=${TRAVIS_TAG#v} clean package -Dmaven.test.skip=true
      after_script: cp KafkaCenter-Core/target/KafkaCenter-Core-${TRAVIS_TAG#v}-release.tar.gz KafkaCenter-Core/target/deploy
      deploy:
        provider: releases
        api_key: $API_KEY
        file_glob: true
        file: KafkaCenter-Core/target/deploy/*
        on:
          tags: true

    - stage: BuildDockerImageforRelease
      install:
        - echo Build Docker Image for Release
      before_script:
        - chmod +x ./scripts/docker-build-release.sh
      script: ./scripts/docker-build-release.sh

stages:
  - ui_build
  - GitHubRelease
  - BuildDockerImageforRelease

notifications:
  email: true