language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/

dist: trusty
jobs:
  include:
    - stage: ui_build
      language: node_js
      node_js: 10.15.2
      script: cd KafkaCenter-Frontend && npm install && npm run build

    - stage: build
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn ${TRAVIS_TAG#v} clean package -Dmaven.test.skip=true

    - stage: GitHubRelease
      script: echo "Deploying to GitHub releases ..." && pwd
      deploy:
        provider: releases
        api_key: $API_KEY
        file_glob: true
        file: $TRAVIS_BUILD_DIR/KafkaCenter-Core/target/*.gz
        skip_cleanup: true
        on:
          tags: true

    - stage: BuildDockerImageforRelease
      script: ./scripts/docker-build-release.sh

stages:
  - ui_build
  - build
  - GitHubRelease
  - BuildDockerImageforRelease

notifications:
  email: true